EIGEN_PATH = 'utils/filenames/eigen/{}_files'
CITYSCAPES_PATH = 'utils/filenames/cityscapes/{}_files'

CITYSCAPES_FOCAL_LENGTH = 2262.52
CITYSCAPES_BASELINE = 0.209313

SCHEDULER_POL_DECAY_PARAM = 0.9
SCHEDULER_STEP_PARAM = 0.5
SCHEDULER_STEP_EPOCHS_PARAM = 10

NUM_LOSSES = 32

IMAGE_EXTENSION = '.png'
